Traceback (most recent call last):
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jfhlewyee/anaconda3/envs/jb/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Descomentar estas l√≠neas si est√° en modo online

#!pip install pyscf
#!pip install geomeTRIC

import pyscf
from pyscf import scf
from pyscf import dft
from pyscf.geomopt.geometric_solver import optimize
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 9>[0;34m()[0m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyscf[39;00m [38;5;28;01mimport[39;00m scf
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyscf[39;00m [38;5;28;01mimport[39;00m dft
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyscf[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgeomopt[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgeometric_solver[39;00m [38;5;28;01mimport[39;00m optimize

File [0;32m~/anaconda3/envs/jb/lib/python3.9/site-packages/pyscf/geomopt/geometric_solver.py:23[0m, in [0;36m<module>[0;34m[0m
[1;32m     21[0m [38;5;28;01mimport[39;00m [38;5;21;01mtempfile[39;00m
[1;32m     22[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m
[0;32m---> 23[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeometric[39;00m
[1;32m     24[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeometric[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmolecule[39;00m
[1;32m     25[0m [38;5;66;03m#from geometric import molecule[39;00m

[0;31mModuleNotFoundError[0m: No module named 'geometric'
ModuleNotFoundError: No module named 'geometric'

